# Use a base image with JDK
FROM samruddhipatil12/open-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from the target directory
COPY target/api-gateway.jar /app/api-gateway.jar

# Start the application
CMD ["java", "-jar","/app/api-gateway.jar"]


