# Use a base image with JDK
FROM samruddhipatil12/open-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/directory-service-0.0.1-SNAPSHOT.jar /app/directory-service.jar

# Run the application
CMD ["java", "-jar", "directory-service.jar"]
