# Use a base image with JDK
FROM samruddhipatil12/openjdk-24-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file from the target directory
COPY target/patient-service.jar /app/patient-service.jar

# Expose the application port (if applicable)
EXPOSE 8080

# Start the application
CMD ["java", "-jar", "/app/patient-service.jar"]
