FROM ubuntu:latest

Run apt update
Run apt install -y openjdk-17-jdk

WORKDIR /app

COPY target/patient-service-0.0.1-SNAPSHOT.jar /app/patient-service.jar

CMD ["java", "-jar", "patient-service.jar"]

