# Use a base image with JDK
FROM samruddhipatil12/open-jdk

# Set the working directory inside the container
WORKDIR /app

COPY target/appointment-service-0.0.1-SNAPSHOT.jar /app/appointment-service.jar

CMD ["java", "-jar","appointment-service.jar"]
