FROM ubuntu:latest

Run apt update
Run apt install -y openjdk-17-jdk

WORKDIR /app

COPY target/appointment-service-0.0.1-SNAPSHOT.jar /app/appointment-service.jar

CMD ["java", "-jar","appointment-service.jar"]

