# Use a base image with JDK
FROM samruddhipatil12/open-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/case-service-0.0.1-SNAPSHOT.jar /app/case-service.jar

# Run the application
CMD ["java", "-jar", "case-service.jar"]
